### ISSUE TITLE
koa-generic-session set error: Cannot read property 'maxAge' of undefined

### ISSUE THREAD

**Issue by sumaolin** [pavelvlasov/koa-generic-session-mongo#14]
``` bash
koa-generic-session set error: Cannot read property 'maxAge' of undefined
    at MongoStore.set$ (f:\Users\dev\bbs\node_modules\koa-generic-session-mongo\dist\store.js:195:33)
    at tryCatch (f:\Users\dev\bbs\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (f:\Users\dev\bbs\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (f:\Users\dev\bbs\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at onFulfilled (f:\Users\dev\bbs\node_modules\co\index.js:65:19)
    at f:\Users\dev\bbs\node_modules\co\index.js:54:5
    at Object.co (f:\Users\dev\bbs\node_modules\co\index.js:50:10)
    at Object.toPromise (f:\Users\dev\bbs\node_modules\co\index.js:118:63)
    at next (f:\Users\dev\bbs\node_modules\co\index.js:99:29)
    at onFulfilled (f:\Users\dev\bbs\node_modules\co\index.js:69:7)
    at f:\Users\dev\bbs\node_modules\co\index.js:54:5
    at Object.co (f:\Users\dev\bbs\node_modules\co\index.js:50:10)
    at Object.toPromise (f:\Users\dev\bbs\node_modules\co\index.js:118:63)
    at next (f:\Users\dev\bbs\node_modules\co\index.js:99:29)
    at onFulfilled (f:\Users\dev\bbs\node_modules\co\index.js:69:7)
    at f:\Users\dev\bbs\node_modules\co\index.js:54:5
```

错误如上，相关的代码

``` javascript
app.use(session({
  store: new MongoStore(config.mongodb)
}));
```

是windows 7 下 node V4.4.3 
koa-generic-session-mongo : v:0.0.25

**Comment by jurgob** [comment]
I have the same error using this store with koa-header-session

**Comment by attekei** [comment]
Experiencing the same error too, in my case in conjunction with [koa-session-minimal](https://github.com/longztian/koa-session-minimal).

**Comment by jurgob** [comment]
I've fixed it with this pull request: https://github.com/pavelvlasov/koa-generic-session-mongo/commit/891d9a2e2ebe061f4ab6cfad2a74f242243ba52b

**Comment by yuu2lee4** [comment]
@jurgob  it is not useful，i use koa-generic-session-mongo with  koa-session-minimal.

**Comment by longztian** [comment]
@jurgob @yuu2lee4 got the same issue reported. I think the store interface need to be updated. Otherwise, the database records will have undefined TTLs. 
https://github.com/pavelvlasov/koa-generic-session-mongo/blob/master/src/store.js#L150

The expected interface should be `set(sid, sess, ttl): set session object for sid, with a ttl (in ms)`, for both [`koa-session-minimal`](https://github.com/longztian/koa-session-minimal#session-store) and [`koa-generic-session`](https://github.com/koajs/generic-session#session-store).

**Comment by pavelvlasov** [comment]
thanks guys, interface is updated in https://github.com/pavelvlasov/koa-generic-session-mongo/commit/6115c41039759e2b0bfc5ea1fb3f7a9007c1e766 (`v0.3.0`)
